### ISSUE TITLE
连接多个网络后代理设置无效

### ISSUE THREAD

**Issue by alexlee728** [yichengchen/clashX#313]
有线网连接后打开ClashX是正常的，接着连接无线网，提示系统代理被其它占用。然后就一直无法设置为系统代理。

关闭无线网，只保留有线网络，再次点击【设置为系统代理】，没有报错，但是设置不成功。必须退出ClashX再次打开。

**Comment by yichengchen** [comment]
Log 或者你debug一下

**Comment by alexlee728** [comment]
试了一下，不能复现了，等复现在看看log

**Comment by hunkchang** [comment]
2020/04/28 18:28:00:155  [info] [TCP] 127.0.0.1:58649 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:28:02:466  [info] [TCP] 127.0.0.1:58683 --> sqimg.qq.com match DomainSuffix using Domestic[DIRECT]
2020/04/28 18:28:02:872  [info] [TCP] 127.0.0.1:58702 --> substrate.office.com match Match using Others[V3 101-穗港[流媒体]]
2020/04/28 18:28:05:153  [info] [TCP] 127.0.0.1:58736 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:28:06:972  [info] [TCP] 127.0.0.1:58770 --> mobile.pipe.aria.microsoft.com match DomainSuffix using Domestic[DIRECT]
2020/04/28 18:28:07:346  [info] [TCP] 127.0.0.1:58772 --> mesu.apple.com match GeoIP using Domestic[DIRECT]
2020/04/28 18:28:10:152  [info] [TCP] 127.0.0.1:58825 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:28:12:276  [info] SOCKS proxy listening at: :1086
2020/04/28 18:28:15:150  [info] [TCP] 127.0.0.1:58911 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:28:16:334  [info] [TCP] 127.0.0.1:58929 --> mtalk.google.com match DomainKeyword using Proxy[V3 101-穗港[流媒体]]
2020/04/28 18:28:20:153  [info] [TCP] 127.0.0.1:58995 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:28:22:419  [info] HTTP proxy listening at: :1087
2020/04/28 18:28:24:972  [info] HTTP proxy listening at: :7890
2020/04/28 18:28:25:148  [info] [TCP] 127.0.0.1:59078 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:28:30:155  [info] [TCP] 127.0.0.1:59160 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:28:31:931  [info] HTTP proxy listening at: :1087
2020/04/28 18:28:43:003  [debug] enableProxy
2020/04/28 18:28:43:646  [info] [TCP] 127.0.0.1:59381 --> mtalk.google.com match DomainKeyword using Proxy[V3 101-穗港[流媒体]]
2020/04/28 18:28:44:044  [info] [TCP] 127.0.0.1:59399 --> clients4.google.com match DomainKeyword using Proxy[V3 101-穗港[流媒体]]
2020/04/28 18:28:44:664  [debug] disableProxy
2020/04/28 18:28:49:402  [debug] checkInstall
2020/04/28 18:28:49:420  [debug] helper version 1.5 require version 1.5
2020/04/28 18:28:49:420  [info] check helper using time: 0.016571044921875
2020/04/28 18:28:49:424  [info] Trying start proxy
2020/04/28 18:28:49:431  [debug] enableProxy
2020/04/28 18:28:49:434  [debug] Auto selecting GLOBAL V1 101-穗港
2020/04/28 18:28:49:434  [debug] Auto selecting Proxy V3 101-穗港[流媒体]
2020/04/28 18:28:49:435  [info] set up autoUpateTimer
2020/04/28 18:28:49:435  [info] Tigger config auto update check
2020/04/28 18:28:49:435  [info] [Auto Upgrade] Bypassing 墙裂 due to time check
2020/04/28 18:28:49:435  [info] [Auto Upgrade] Bypassing SoCloud due to time check
2020/04/28 18:28:49:438  [info] Saving Remote Config Setting
2020/04/28 18:28:49:442  [debug] trafficWebSocket did Connect
2020/04/28 18:28:49:442  [debug] loggingWebSocket did Connect
2020/04/28 18:28:49:447  [info] HTTP proxy listening at: :7890
2020/04/28 18:28:49:447  [info] SOCKS proxy listening at: :7891
2020/04/28 18:28:49:677  [info] [TCP] 127.0.0.1:59509 --> e.crashlytics.com match Match using Others[V3 101-穗港[流媒体]]
2020/04/28 18:28:50:147  [info] [TCP] 127.0.0.1:59527 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:28:50:484  [info] [TCP] 127.0.0.1:59529 --> e.crashlytics.com match Match using Others[V3 101-穗港[流媒体]]
2020/04/28 18:28:51:154  [info] [TCP] 127.0.0.1:59547 --> imbxpkxrih match Match using Others[V3 101-穗港[流媒体]]
2020/04/28 18:28:51:169  [info] [TCP] 127.0.0.1:59549 --> tgunqyahcgr match Match using Others[V3 101-穗港[流媒体]]
2020/04/28 18:28:51:311  [info] [TCP] 127.0.0.1:59548 --> yhajbkwitkjzsc match Match using Others[V3 101-穗港[流媒体]]

**Comment by hunkchang** [comment]
复现的DEBUG信息如下：

2020/04/28 18:30:00:143  [debug] [DNS] sqt.gtimg.cn --> 183.3.235.49
2020/04/28 18:30:00:151  [info] [TCP] 127.0.0.1:60741 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:30:02:788  [debug] [DNS] substrate.office.com --> 13.107.18.11
2020/04/28 18:30:02:869  [info] [TCP] 127.0.0.1:60775 --> substrate.office.com match Match using Others[V3 101-穗港[流媒体]]
2020/04/28 18:30:02:946  [debug] [DNS] e.crashlytics.com --> 54.225.219.77
2020/04/28 18:30:03:003  [info] [TCP] 127.0.0.1:60777 --> e.crashlytics.com match Match using Others[V3 101-穗港[流媒体]]
2020/04/28 18:30:03:003  [debug] Optional(<WKNavigation: 0x7fdad8d05640>)
2020/04/28 18:30:03:162  [info] [TCP] 127.0.0.1:60782 --> at.alicdn.com match DomainSuffix using Domestic[DIRECT]
2020/04/28 18:30:05:144  [debug] [DNS] sqt.gtimg.cn --> 183.3.235.49
2020/04/28 18:30:05:159  [info] [TCP] 127.0.0.1:60818 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:30:09:677  [info] [TCP] 127.0.0.1:60852 --> mobile.pipe.aria.microsoft.com match DomainSuffix using Domestic[DIRECT]
2020/04/28 18:30:10:143  [debug] [DNS] sqt.gtimg.cn --> 183.3.235.49
2020/04/28 18:30:10:156  [info] [TCP] 127.0.0.1:60905 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:30:10:649  [info] SOCKS proxy listening at: :1086
2020/04/28 18:30:15:142  [debug] [DNS] sqt.gtimg.cn --> 183.3.235.49
2020/04/28 18:30:15:155  [info] [TCP] 127.0.0.1:60987 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:30:17:608  [info] HTTP proxy listening at: :1087
2020/04/28 18:30:35:986  [debug] enableProxy
2020/04/28 18:30:36:631  [info] [TCP] 127.0.0.1:61355 --> mtalk.google.com match DomainKeyword using Proxy[V3 101-穗港[流媒体]]
2020/04/28 18:30:37:096  [info] [TCP] 127.0.0.1:61357 --> clients4.google.com match DomainKeyword using Proxy[V3 101-穗港[流媒体]]
2020/04/28 18:30:37:563  [debug] disableProxy
2020/04/28 18:30:41:293  [debug] checkInstall
2020/04/28 18:30:41:309  [debug] helper version 1.5 require version 1.5
2020/04/28 18:30:41:309  [info] check helper using time: 0.014258027076721191
2020/04/28 18:30:41:315  [info] Trying start proxy
2020/04/28 18:30:41:323  [debug] enableProxy
2020/04/28 18:30:41:326  [debug] Auto selecting GLOBAL V1 101-穗港
2020/04/28 18:30:41:326  [debug] Auto selecting Proxy V3 101-穗港[流媒体]
2020/04/28 18:30:41:326  [info] set up autoUpateTimer
2020/04/28 18:30:41:327  [info] Tigger config auto update check
2020/04/28 18:30:41:327  [info] [Auto Upgrade] Bypassing 墙裂 due to time check
2020/04/28 18:30:41:327  [info] [Auto Upgrade] Bypassing SoCloud due to time check
2020/04/28 18:30:41:330  [info] Saving Remote Config Setting
2020/04/28 18:30:41:334  [debug] trafficWebSocket did Connect
2020/04/28 18:30:41:334  [debug] loggingWebSocket did Connect
2020/04/28 18:30:41:340  [info] HTTP proxy listening at: :7890
2020/04/28 18:30:41:340  [info] SOCKS proxy listening at: :7891
2020/04/28 18:30:43:010  [debug] [DNS] resolve otyqhudw error: lookup otyqhudw: no such host
2020/04/28 18:30:43:049  [debug] [DNS] resolve avjddswdbwkoe error: lookup avjddswdbwkoe: no such host
2020/04/28 18:30:43:067  [info] [TCP] 127.0.0.1:61483 --> otyqhudw match Match using Others[V3 101-穗港[流媒体]]
2020/04/28 18:30:43:112  [info] [TCP] 127.0.0.1:61481 --> avjddswdbwkoe match Match using Others[V3 101-穗港[流媒体]]
2020/04/28 18:30:43:159  [debug] [DNS] resolve vrdvebb error: lookup vrdvebb: no such host
2020/04/28 18:30:43:237  [info] [TCP] 127.0.0.1:61482 --> vrdvebb match Match using Others[V3 101-穗港[流媒体]]
2020/04/28 18:30:45:144  [debug] [DNS] sqt.gtimg.cn --> 183.3.235.49
2020/04/28 18:30:45:159  [info] [TCP] 127.0.0.1:61519 --> sqt.gtimg.cn match GeoIP using Domestic[DIRECT]
2020/04/28 18:30:45:444  [debug] [DNS] p18-caldav.icloud.com --> 17.248.160.77
2020/04/28 18:30:45:797  [info] [TCP] 127.0.0.1:61537 --> p18-caldav.icloud.com match Match using Others[V3 101-穗港[流媒体]]
